# Generated by Django 2.1.4 on 2019-01-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsaverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
