export const USER_FETCHED_SUCCESS = "USER_FETCHED_SUCCESS";
export const USER_FETCHED_FAILED = "USER_FETCHED_FAILD";
export const EMAIL_FETCHED_SUCCESS = "EMAIL_FETCHED_SUCCESS";
export const EMAIL_FETCHED_FAILED = "EMAIL_FETCHED_FAILED";

export const GET_FAVPHOTOS_REQUEST = "GET_FAVPHOTOS_REQUEST";
export const GET_FAVPHOTOS_SUCCESS = "GET_FAVPHOTOS_SUCCESS";
export const GET_FAVPHOTOS_FAIELD = "GET_FAVPHOTOS_FAIELD";

export const TOGGLE_LIKE_REQUEST = "TOGGLE_LIKE_REQUEST";
export const TOGGLE_LIKE_ADDED_SUCCESS = "TOGGLE_LIKE_ADDED_SUCCESS";
export const TOGGLE_LIKE_REMOVE_SUCCESS = "TOGGLE_LIKE_REMOVE_SUCCESS";
export const TOGGLE_LIKE_FAIELD = "TOGGLE_LIKE_FAIELD";
