export const USER_FETCHED_SUCCESS = "USER_FETCHED_SUCCESS";
export const USER_FETCHED_FAILED = "USER_FETCHED_FAILD";
export const EMAIL_FETCHED_SUCCESS = "EMAIL_FETCHED_SUCCESS";
export const EMAIL_FETCHED_FAILED = "EMAIL_FETCHED_FAILED";
